"""Structured contracts shared by the agent architecture.

These values are deliberately independent from the career domain.  They make
the perception, planning, policy, execution, and memory boundaries explicit
without forcing existing tools to know about a particular agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Mapping
from uuid import uuid4


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


class ToolEffect(str, Enum):
    """The highest external effect a tool call may have."""

    OBSERVE = "observe"
    READ = "read"
    WRITE = "write"
    SUBMIT = "submit"
    REPAIR = "repair"


@dataclass(frozen=True)
class Observation:
    """A normalized view of environment state available to the Agent Core."""

    kind: str
    source: str
    payload: Mapping[str, Any]
    observed_at: str = field(default_factory=_now)
    observation_id: str = field(default_factory=lambda: uuid4().hex)


@dataclass(frozen=True)
class ToolCall:
    """A planned tool invocation which must be authorized before execution."""

    tool_name: str
    parameters: Mapping[str, Any]
    effect: ToolEffect = ToolEffect.READ
    purpose: str = ""
    context: Mapping[str, Any] = field(default_factory=dict)
    call_id: str = field(default_factory=lambda: uuid4().hex)


@dataclass(frozen=True)
class PolicyDecision:
    """The auditable result of evaluating one planned action."""

    allowed: bool
    code: str
    reason: str
    policy: str
    decided_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class ToolResult:
    """A structured result returned to the Agent Core."""

    call_id: str
    tool_name: str
    effect: ToolEffect
    ok: bool
    output: Any = None
    error: str | None = None
    policy_decision: PolicyDecision | None = None
    started_at: str = field(default_factory=_now)
    finished_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class Plan:
    """An ordered plan generated by deterministic logic or an LLM."""

    objective: str
    steps: tuple[ToolCall, ...]
    plan_id: str = field(default_factory=lambda: uuid4().hex)
    created_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class AgentLoopContext:
    """Read-only context available while choosing one bounded action."""

    objective: str
    round_index: int
    observation: Observation
    remaining_actions: tuple[ToolCall, ...]
    short_term_observations: tuple[Observation, ...]
    tool_results: tuple[ToolResult, ...]
    long_term_memory_hits: tuple[Mapping[str, Any], ...] = ()


@dataclass(frozen=True)
class AgentThought:
    """Auditable decision summary, not hidden chain-of-thought."""

    objective: str
    observation_id: str
    strategy: str
    summary: str
    plan: tuple[str, ...]
    selected_action: ToolCall
    reflection: str = ""
    self_criticism: str = ""
    memory_observation_ids: tuple[str, ...] = ()
    long_term_memory_hit_count: int = 0
    thought_id: str = field(default_factory=lambda: uuid4().hex)
    created_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class MemoryUpdate:
    """Memory changes made after one action produced a new observation."""

    round_id: str
    tool_call_id: str
    observation_id: str
    short_term_updated: bool
    long_term_updated: bool
    long_term_namespace: str | None = None
    summary: str = ""
    updated_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class AgentRound:
    """One Perception -> Thought -> Action -> Observation -> Memory cycle."""

    index: int
    input_observation: Observation
    thought: AgentThought
    action: ToolCall
    policy_decision: PolicyDecision | None
    tool_result: ToolResult
    new_observation: Observation
    memory_update: MemoryUpdate
    status: str
    round_id: str
    parallel_group_id: str | None = None


@dataclass(frozen=True)
class AgentLoopResult:
    """The complete, ordered closed-loop trajectory for one objective."""

    plan: Plan
    rounds: tuple[AgentRound, ...]
    observations: tuple[Observation, ...]
    status: str

    @property
    def results(self) -> tuple[ToolResult, ...]:
        return tuple(round_.tool_result for round_ in self.rounds)

    @property
    def thoughts(self) -> tuple[AgentThought, ...]:
        return tuple(round_.thought for round_ in self.rounds)

    @property
    def memory_updates(self) -> tuple[MemoryUpdate, ...]:
        return tuple(round_.memory_update for round_ in self.rounds)

    @property
    def outputs(self) -> dict[str, Any]:
        return {
            result.tool_name: result.output
            for result in self.results
            if result.ok
        }


@dataclass(frozen=True)
class AgentRunResult:
    """The complete result of one bounded plan execution."""

    plan: Plan
    results: tuple[ToolResult, ...]
    observations: tuple[Observation, ...]
    status: str

    @property
    def outputs(self) -> dict[str, Any]:
        return {
            result.tool_name: result.output
            for result in self.results
            if result.ok
        }


@dataclass(frozen=True)
class StrategyRunResult:
    """A normalized result from any Agent Core reasoning strategy."""

    strategy: str
    output: str
    status: str
    plan: tuple[str, ...] = ()
    trace: tuple[Mapping[str, Any], ...] = ()
    tool_results: tuple[ToolResult, ...] = ()


@dataclass(frozen=True)
class AgentEvaluationRequest:
    """One read-only round snapshot submitted to a registered evaluator."""

    round_id: str
    inputs: Mapping[str, Any]
    targets: Mapping[str, Any] = field(default_factory=dict)
    metadata: Mapping[str, Any] = field(default_factory=dict)
    evaluation_id: str = field(default_factory=lambda: uuid4().hex)
    created_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class AgentEvaluationResult:
    """Structured assessment returned to Agent Core for one round."""

    evaluator: str
    round_id: str
    status: str
    metrics: Mapping[str, Any]
    summary: str = ""
    recommendations: tuple[str, ...] = ()
    evaluation_id: str = field(default_factory=lambda: uuid4().hex)
    evaluated_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class RecoveryAction:
    """One bounded action proposed for a non-success terminal state."""

    action: str
    description: str
    automatic: bool
    requires_user: bool = False
    parameters: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class RecoveryPlan:
    """Auditable resolution plan that never invents a successful outcome.

    ``retry_allowed`` means a single-application retry may be considered only
    after every required action and evidence condition in this plan succeeds.
    It is never permission for an immediate or whole-batch replay.
    """

    status: str
    strategy: str
    actions: tuple[RecoveryAction, ...]
    retry_allowed: bool
    retry_after_seconds: int | None = None
    retry_scope: str = "single_application"
    retry_condition: str = ""
    evidence_required: tuple[str, ...] = ()
    reason: str = ""


@dataclass(frozen=True)
class RecoveryActionResult:
    """Audited outcome of one planned recovery action."""

    action: str
    status: str
    automatic: bool
    evidence: tuple[str, ...] = ()
    message: str = ""
    details: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class RecoveryExecutionResult:
    """Bounded recovery outcome returned to Agent Core."""

    strategy: str
    status: str
    actions: tuple[RecoveryActionResult, ...]
    evidence: tuple[str, ...] = ()
    retry_ready: bool = False
    retry_scope: str = "single_application"
    reason: str = ""
    agent_loops: tuple[AgentLoopResult, ...] = ()
    execution_id: str = field(default_factory=lambda: uuid4().hex)
    executed_at: str = field(default_factory=_now)


@dataclass(frozen=True)
class AgentCoreCapabilities:
    """Inspectable composition used by diagnostics and architecture tests."""

    strategies: tuple[str, ...]
    tools: tuple[str, ...]
    recovery_planners: tuple[str, ...]
    evaluators: tuple[str, ...]
    conversation_enabled: bool
    tool_chain_enabled: bool = True
    concurrent_read_enabled: bool = True
    evaluation_history_enabled: bool = True
    recovery_executors: tuple[str, ...] = ()
    closed_loop_enabled: bool = True
