from __future__ import annotations

import json
from typing import Any


def render_batch_fill_runner(
    summary_items: list[dict[str, Any]],
    required_resume_pdf: dict[str, Any] | None = None,
    required_resume_source_dir: dict[str, Any] | None = None,
) -> str:
    runnable_items = [
        {
            "company": item.get("company") or "Unknown Company",
            "title": item.get("title") or "Unknown Role",
            "script_path": item.get("runtime_script_path") or item.get("fill_script_path"),
            "package_dir": item.get("package_dir"),
            "upload_resume_path": item.get("upload_resume_path"),
            "upload_resume_pdf_sha256": item.get("upload_resume_pdf_sha256"),
            "required_resume_pdf": item.get("required_resume_pdf"),
            "required_resume_source_dir": item.get("required_resume_source_dir"),
        }
        for item in summary_items
        if item.get("runtime_script_path") or item.get("fill_script_path")
    ]
    return "\n".join(
        [
            'const { spawn } = require("child_process");',
            'const crypto = require("crypto");',
            'const fs = require("fs");',
            'const path = require("path");',
            "",
            f"const applications = {json.dumps(runnable_items, indent=2)};",
            f"const requiredResume = {json.dumps(required_resume_pdf, indent=2)};",
            f"const requiredResumeSourceDir = {json.dumps(required_resume_source_dir, indent=2)};",
            "const COMPLETION_MARKERS = [",
            "  'Submit gate:',",
            "  'Submission confirmed:',",
            "  'Submit clicked but confirmation not detected:',",
            "  'Email verification required:',",
            "  'Submission processing error:',",
            "];",
            "",
            "function runApplication(application) {",
            "  return new Promise((resolve) => {",
            '    const child = spawn("node", [application.script_path], { stdio: ["inherit", "pipe", "pipe"] });',
            "    let stdout = '';",
            "    child.stdout.on('data', (chunk) => {",
            "      const text = chunk.toString();",
            "      stdout += text;",
            "      process.stdout.write(text);",
            "    });",
            "    child.stderr.on('data', (chunk) => process.stderr.write(chunk));",
            "    child.on('error', (error) => resolve({ status: 1, stdout, error }));",
            "    child.on('close', (status) => resolve({ status, stdout }));",
            "  });",
            "}",
            "",
            "function sha256File(filePath) {",
            "  const hash = crypto.createHash('sha256');",
            "  hash.update(fs.readFileSync(filePath));",
            "  return hash.digest('hex');",
            "}",
            "",
            "function isInsidePath(childPath, parentPath) {",
            "  const relative = path.relative(parentPath, childPath);",
            "  return relative && !relative.startsWith('..') && !path.isAbsolute(relative);",
            "}",
            "",
            "function runtimeResumeFile(application) {",
            "  if (!application.script_path || !fs.existsSync(application.script_path)) return null;",
            "  const script = fs.readFileSync(application.script_path, 'utf8');",
            "  const match = script.match(/\"resumeFile\"\\s*:\\s*(\"(?:[^\"\\\\]|\\\\.)*\"|null)/);",
            "  if (!match || match[1] === 'null') return null;",
            "  return JSON.parse(match[1]);",
            "}",
            "",
            "function verifyResume(application) {",
            "  if (!application.upload_resume_path) {",
            "    throw new Error(`${application.company} - ${application.title}: missing required PDF resume upload path`);",
            "  }",
            "  const effectiveRequiredResume = requiredResume || (application.required_resume_pdf ? { path: application.required_resume_pdf } : null);",
            "  const effectiveRequiredSourceDir = requiredResumeSourceDir || (application.required_resume_source_dir ? { path: application.required_resume_source_dir } : null);",
            "  const resumePath = path.resolve(application.upload_resume_path);",
            "  if (path.extname(resumePath).toLowerCase() !== '.pdf') {",
            "    throw new Error(`${application.company} - ${application.title}: resume upload must be a PDF: ${resumePath}`);",
            "  }",
            "  if (!fs.existsSync(resumePath) || !fs.statSync(resumePath).isFile()) {",
            "    throw new Error(`${application.company} - ${application.title}: resume upload PDF does not exist: ${resumePath}`);",
            "  }",
            "  const runtimeResume = runtimeResumeFile(application);",
            "  if (runtimeResume) {",
            "    const runtimeResumePath = path.resolve(path.dirname(application.script_path), runtimeResume);",
            "    if (runtimeResumePath !== resumePath) {",
            "      throw new Error(`${application.company} - ${application.title}: runtime resumeFile does not match summary upload_resume_path: ${runtimeResumePath}; expected: ${resumePath}`);",
            "    }",
            "  }",
            "  if (application.package_dir) {",
            "    const packagePath = path.resolve(application.package_dir);",
            "    if (isInsidePath(resumePath, packagePath)) {",
            "      throw new Error(`${application.company} - ${application.title}: resume upload PDF must be an original external path, not package-local: ${resumePath}`);",
            "    }",
            "  }",
            "  if (effectiveRequiredSourceDir) {",
            "    const requiredSourcePath = path.resolve(effectiveRequiredSourceDir.path);",
            "    if (!isInsidePath(resumePath, requiredSourcePath)) {",
            "      throw new Error(`${application.company} - ${application.title}: resume upload PDF must come from required resume source dir: ${resumePath}; expected under: ${requiredSourcePath}`);",
            "    }",
            "  }",
            "  const resumeSha = sha256File(resumePath);",
            "  if (application.upload_resume_pdf_sha256 && resumeSha !== application.upload_resume_pdf_sha256) {",
            "    throw new Error(`${application.company} - ${application.title}: resume upload PDF hash does not match prepared summary: ${resumeSha}; expected: ${application.upload_resume_pdf_sha256}`);",
            "  }",
            "  if (effectiveRequiredResume) {",
            "    const requiredPath = path.resolve(effectiveRequiredResume.path);",
            "    if (resumePath !== requiredPath) {",
            "      throw new Error(`${application.company} - ${application.title}: resume upload PDF does not match required path: ${resumePath}; expected: ${requiredPath}`);",
            "    }",
            "    if (effectiveRequiredResume.sha256 && resumeSha !== effectiveRequiredResume.sha256) {",
            "      throw new Error(`${application.company} - ${application.title}: resume upload PDF hash does not match required PDF: ${resumeSha}; expected: ${effectiveRequiredResume.sha256}`);",
            "    }",
            "  }",
            "  return { path: resumePath, sha256: resumeSha };",
            "}",
            "",
            "function verifyAllResumes() {",
            "  const failures = [];",
            "  for (const application of applications) {",
            "    try {",
            "      verifyResume(application);",
            "    } catch (error) {",
            "      failures.push(error.message);",
            "    }",
            "  }",
            "  if (failures.length) {",
            "    console.error('Resume preflight failed; no browser runtime executed.');",
            "    for (const failure of failures) console.error(failure);",
            "    process.exit(1);",
            "  }",
            "  console.log(`Resume preflight verified for ${applications.length} application(s).`);",
            "}",
            "",
            "(async () => {",
            "  verifyAllResumes();",
            "  for (const application of applications) {",
            '    console.log(`Preparing ${application.company} - ${application.title}`);',
            "    const result = await runApplication(application);",
            "    if (result.status !== 0) {",
            '      console.error(`Stopped after ${application.company} - ${application.title}`);',
            "      if (result.error) console.error(result.error.message);",
            "      process.exit(result.status || 1);",
            "    }",
            "    if (!result.stdout || !COMPLETION_MARKERS.some((marker) => result.stdout.includes(marker))) {",
            '      console.error(`Stopped after ${application.company} - ${application.title}: runtime completion was not confirmed`);',
            "      process.exit(1);",
            "    }",
            "  }",
            "",
            "  console.log('Runtime completed for each application.');",
            "  console.log('Submit policy: final Submit is automatic unless JOB_AGENT_SUBMIT_COMPLETE=0.');",
            "})().catch((error) => {",
            "  console.error(error);",
            "  process.exit(1);",
            "});",
        ]
    ) + "\n"
